import type { Lesson } from '../types.js';

export const lessons: readonly Lesson[] = [
  {
    id: 1,
    title: 'Literal Characters',
    description: 'Match the exact word "cat" in the text',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: 'cat', shouldMatch: true },
      { input: 'dog', shouldMatch: false },
      { input: 'catch', shouldMatch: true },
      { input: 'scat', shouldMatch: true },
      { input: 'CAT', shouldMatch: false },
    ],
    hint: 'Type the exact characters you want to match',
    solution: 'cat',
  },
  {
    id: 2,
    title: 'The Dot Metacharacter',
    description: 'Match "c", any single character, then "t" (like cat, cot, cut)',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: 'cat', shouldMatch: true },
      { input: 'cot', shouldMatch: true },
      { input: 'cut', shouldMatch: true },
      { input: 'ct', shouldMatch: false },
      { input: 'cart', shouldMatch: false },
    ],
    hint: 'Use . to match any single character',
    solution: 'c.t',
  },
  {
    id: 3,
    title: 'Character Classes',
    description: 'Match "cat" or "bat" (but not "rat")',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: 'cat', shouldMatch: true },
      { input: 'bat', shouldMatch: true },
      { input: 'rat', shouldMatch: false },
      { input: 'hat', shouldMatch: false },
      { input: 'category', shouldMatch: true },
    ],
    hint: 'Use [abc] to match any character in the brackets',
    solution: '[cb]at',
  },
  {
    id: 4,
    title: 'Character Ranges',
    description: 'Match any single digit (0-9)',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: '5', shouldMatch: true },
      { input: 'a', shouldMatch: false },
      { input: '42', shouldMatch: true },
      { input: 'abc', shouldMatch: false },
      { input: 'room 123', shouldMatch: true },
    ],
    hint: 'Use [0-9] to match any digit',
    solution: '[0-9]',
  },
  {
    id: 5,
    title: 'Negated Character Classes',
    description: 'Match any character that is NOT a vowel (aeiou)',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: 'b', shouldMatch: true },
      { input: 'a', shouldMatch: false },
      { input: 'xyz', shouldMatch: true },
      { input: 'hello', shouldMatch: true },
      { input: 'aaa', shouldMatch: false },
    ],
    hint: 'Use [^abc] to match any character NOT in the brackets',
    solution: '[^aeiou]',
  },
  {
    id: 6,
    title: 'Shorthand Character Classes',
    description: 'Match any word character (letter, digit, or underscore)',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: 'a', shouldMatch: true },
      { input: '5', shouldMatch: true },
      { input: '_', shouldMatch: true },
      { input: ' ', shouldMatch: false },
      { input: 'hello_123', shouldMatch: true },
    ],
    hint: 'Use \\w to match word characters',
    solution: '\\w',
  },
  {
    id: 7,
    title: 'The Plus Quantifier',
    description: 'Match one or more digits in a row',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: '123', shouldMatch: true },
      { input: '5', shouldMatch: true },
      { input: 'abc', shouldMatch: false },
      { input: 'room 42', shouldMatch: true },
      { input: 'no digits', shouldMatch: false },
    ],
    hint: 'Use + to match one or more of the preceding pattern',
    solution: '\\d+',
  },
  {
    id: 8,
    title: 'The Star Quantifier',
    description: 'Match "go" followed by zero or more "o"s (go, goo, gooo)',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: 'go', shouldMatch: true },
      { input: 'goo', shouldMatch: true },
      { input: 'gooo', shouldMatch: true },
      { input: 'g', shouldMatch: false },
      { input: 'good', shouldMatch: true },
    ],
    hint: 'Use * to match zero or more of the preceding pattern',
    solution: 'goo*',
  },
  {
    id: 9,
    title: 'The Question Mark Quantifier',
    description: 'Match "color" or "colour" (u is optional)',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: 'color', shouldMatch: true },
      { input: 'colour', shouldMatch: true },
      { input: 'colr', shouldMatch: false },
      { input: 'colorful', shouldMatch: true },
      { input: 'colourful', shouldMatch: true },
    ],
    hint: 'Use ? to make the preceding character optional',
    solution: 'colou?r',
  },
  {
    id: 10,
    title: 'Anchors - Start of String',
    description: 'Match "cat" only at the start of the string',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: 'cat', shouldMatch: true },
      { input: 'category', shouldMatch: true },
      { input: 'the cat', shouldMatch: false },
      { input: 'a cat', shouldMatch: false },
      { input: 'catch', shouldMatch: true },
    ],
    hint: 'Use ^ to anchor to the start of the string',
    solution: '^cat',
  },
  {
    id: 11,
    title: 'Anchors - End of String',
    description: 'Match "end" only at the end of the string',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: 'end', shouldMatch: true },
      { input: 'the end', shouldMatch: true },
      { input: 'ending', shouldMatch: false },
      { input: 'end of story', shouldMatch: false },
      { input: 'backend', shouldMatch: true },
    ],
    hint: 'Use $ to anchor to the end of the string',
    solution: 'end$',
  },
  {
    id: 12,
    title: 'Word Boundaries',
    description: 'Match the word "cat" as a complete word (not in "catch" or "scat")',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: 'cat', shouldMatch: true },
      { input: 'the cat', shouldMatch: true },
      { input: 'catch', shouldMatch: false },
      { input: 'scat', shouldMatch: false },
      { input: 'cat!', shouldMatch: true },
    ],
    hint: 'Use \\b for word boundaries',
    solution: '\\bcat\\b',
  },
  {
    id: 13,
    title: 'Alternation',
    description: 'Match "cat" or "dog"',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: 'cat', shouldMatch: true },
      { input: 'dog', shouldMatch: true },
      { input: 'bird', shouldMatch: false },
      { input: 'my cat', shouldMatch: true },
      { input: 'a dog', shouldMatch: true },
    ],
    hint: 'Use | for alternation (OR)',
    solution: 'cat|dog',
  },
  {
    id: 14,
    title: 'Grouping',
    description: 'Match "re" followed by one or more of "pe" or "de"',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: 'repeat', shouldMatch: true },
      { input: 'repent', shouldMatch: true },
      { input: 'redemption', shouldMatch: true },
      { input: 'react', shouldMatch: false },
      { input: 'repepe', shouldMatch: true },
    ],
    hint: 'Use parentheses () to group patterns',
    solution: 're(pe|de)',
  },
  {
    id: 15,
    title: 'Escaping Special Characters',
    description: 'Match a literal dot "." character',
    type: 'match',
    belt: 'white',
    testCases: [
      { input: '.', shouldMatch: true },
      { input: 'a', shouldMatch: false },
      { input: 'file.txt', shouldMatch: true },
      { input: 'hello', shouldMatch: false },
      { input: '...', shouldMatch: true },
    ],
    hint: 'Use backslash \\ to escape special characters',
    solution: '\\.',
  },
  {
    id: 16,
    title: 'Extract IPv4 Addresses',
    description: 'Extract valid IPv4 addresses from server logs (simplified - just pattern match)',
    type: 'match',
    belt: 'yellow',
    testCases: [
      { input: '192.168.1.1 - GET /index.html', shouldMatch: true },
      { input: '10.0.0.255 - POST /api/users', shouldMatch: true },
      { input: '127.0.0.1 - ERROR 404', shouldMatch: true },
      { input: 'No IP address here', shouldMatch: false },
      { input: '172.16.254.1 connected', shouldMatch: true },
    ],
    hint: 'Match 1-3 digits, then dot, repeated 4 times. Use \\d{1,3} for digits',
    solution: '\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}',
  },
  {
    id: 17,
    title: 'Extract Email Addresses',
    description: 'Match email addresses (simplified pattern)',
    type: 'match',
    belt: 'yellow',
    testCases: [
      { input: 'Contact me at user@example.com', shouldMatch: true },
      { input: 'admin@site.org is the admin', shouldMatch: true },
      { input: 'invalid.email.com', shouldMatch: false },
      { input: 'test_user@domain.co.uk works', shouldMatch: true },
      { input: 'no email here', shouldMatch: false },
    ],
    hint: 'word chars + @ + word chars + dot + word chars. Remember \\w for word characters',
    solution: '\\w+@\\w+\\.\\w+',
  },
  {
    id: 18,
    title: 'Extract URLs',
    description: 'Match HTTP/HTTPS URLs',
    type: 'match',
    belt: 'yellow',
    testCases: [
      { input: 'Visit https://example.com for more', shouldMatch: true },
      { input: 'Check out http://site.org', shouldMatch: true },
      { input: 'ftp://wrong.com should not match', shouldMatch: false },
      { input: 'https://github.com/user/repo', shouldMatch: true },
      { input: 'no url here', shouldMatch: false },
    ],
    hint: 'Match http OR https, then ://, then word chars/dots/slashes. Use (http|https)',
    solution: '(http|https)://[\\w./]+',
  },
  {
    id: 19,
    title: 'Parse Dates (MM/DD/YYYY)',
    description: 'Match dates in MM/DD/YYYY format',
    type: 'match',
    belt: 'yellow',
    testCases: [
      { input: 'Event on 12/25/2024', shouldMatch: true },
      { input: 'Born on 01/15/1990', shouldMatch: true },
      { input: 'Invalid date format 2024-12-25', shouldMatch: false },
      { input: 'Meeting: 06/30/2025 at noon', shouldMatch: true },
      { input: 'No date in this text', shouldMatch: false },
    ],
    hint: 'Match 2 digits, slash, 2 digits, slash, 4 digits. Use \\d{2} and \\d{4}',
    solution: '\\d{2}/\\d{2}/\\d{4}',
  },
  {
    id: 20,
    title: 'Extract Phone Numbers',
    description: 'Match US phone numbers (XXX-XXX-XXXX)',
    type: 'match',
    belt: 'yellow',
    testCases: [
      { input: 'Call me at 555-123-4567', shouldMatch: true },
      { input: 'Office: 800-555-0199', shouldMatch: true },
      { input: 'Invalid 12345', shouldMatch: false },
      { input: 'Mobile 415-867-5309', shouldMatch: true },
      { input: 'No phone number', shouldMatch: false },
    ],
    hint: 'Match 3 digits, dash, 3 digits, dash, 4 digits',
    solution: '\\d{3}-\\d{3}-\\d{4}',
  },
  {
    id: 21,
    title: 'Extract Hashtags',
    description: 'Match social media hashtags',
    type: 'match',
    belt: 'yellow',
    testCases: [
      { input: 'Love this #regex tutorial', shouldMatch: true },
      { input: '#coding is fun #development', shouldMatch: true },
      { input: 'No hashtags here', shouldMatch: false },
      { input: 'Check out #JavaScript_2024', shouldMatch: true },
      { input: 'Just a # symbol', shouldMatch: false },
    ],
    hint: 'Match # followed by one or more word characters',
    solution: '#\\w+',
  },
  {
    id: 22,
    title: 'Parse Hex Colors',
    description: 'Match hex color codes (#RGB or #RRGGBB)',
    type: 'match',
    belt: 'yellow',
    testCases: [
      { input: 'Primary color: #ff0000', shouldMatch: true },
      { input: 'Use #fff for white', shouldMatch: true },
      { input: 'Border color #a1b2c3', shouldMatch: true },
      { input: 'Invalid color rgb(255,0,0)', shouldMatch: false },
      { input: 'Background: #123', shouldMatch: true },
    ],
    hint: 'Match # followed by exactly 3 or 6 hex digits [0-9a-fA-F]. Use {3} or {6}',
    solution: '#[0-9a-fA-F]{3}([0-9a-fA-F]{3})?',
  },
  {
    id: 23,
    title: 'Repeated Words (Backreference)',
    description: 'Match repeated words like "bye bye" or "go go"',
    type: 'match',
    belt: 'orange',
    testCases: [
      { input: 'bye bye', shouldMatch: true },
      { input: 'go go', shouldMatch: true },
      { input: 'this is is fine', shouldMatch: true },
      { input: 'hello world', shouldMatch: false },
      { input: 'go-go', shouldMatch: false },
    ],
    hint: 'Capture a word, then match whitespace and the same word again using \\1',
    solution: '\\b(\\w+)\\s+\\1\\b',
  },
  {
    id: 24,
    title: 'Quoted Strings',
    description: 'Match text inside double quotes',
    type: 'match',
    belt: 'orange',
    testCases: [
      { input: 'She said "hello"', shouldMatch: true },
      { input: '"just quotes"', shouldMatch: true },
      { input: 'no quotes here', shouldMatch: false },
      { input: '"unclosed', shouldMatch: false },
      { input: 'quote "inside" text', shouldMatch: true },
    ],
    hint: 'Match a " then any non-quote chars, then another "',
    solution: '"[^"]*"',
  },
  {
    id: 25,
    title: 'US ZIP Codes',
    description: 'Match ZIP codes like 12345 or 12345-6789',
    type: 'match',
    belt: 'orange',
    testCases: [
      { input: '90210', shouldMatch: true },
      { input: '12345-6789', shouldMatch: true },
      { input: 'zip 1234', shouldMatch: false },
      { input: '123456', shouldMatch: false },
      { input: 'code: 02134', shouldMatch: true },
    ],
    hint: 'Match 5 digits with an optional -4 extension',
    solution: '\\b\\d{5}(-\\d{4})?\\b',
  },
  {
    id: 26,
    title: '24-Hour Time',
    description: 'Match times like 09:05 or 23:59',
    type: 'match',
    belt: 'orange',
    testCases: [
      { input: '00:00', shouldMatch: true },
      { input: '23:59', shouldMatch: true },
      { input: '24:00', shouldMatch: false },
      { input: '7:30', shouldMatch: false },
      { input: 'Meeting at 09:05', shouldMatch: true },
    ],
    hint: 'Hours 00-23 and minutes 00-59',
    solution: '\\b([01]\\d|2[0-3]):[0-5]\\d\\b',
  },
] as const;

export const getLesson = (id: number): Lesson | undefined =>
  lessons.find(lesson => lesson.id === id);

export const getNextLesson = (currentId: number): Lesson | undefined =>
  lessons.find(lesson => lesson.id === currentId + 1);
