import type { Lesson } from '../types.js';

export const lessons: readonly Lesson[] = [
  {
    id: 1,
    title: 'Literal Characters',
    description: 'Match the exact word "cat" in the text',
    type: 'match',
    testCases: [
      { input: 'cat', shouldMatch: true },
      { input: 'dog', shouldMatch: false },
      { input: 'catch', shouldMatch: true },
      { input: 'scat', shouldMatch: true },
      { input: 'CAT', shouldMatch: false },
    ],
    hint: 'Type the exact characters you want to match',
    solution: 'cat',
  },
  {
    id: 2,
    title: 'The Dot Metacharacter',
    description: 'Match "c", any single character, then "t" (like cat, cot, cut)',
    type: 'match',
    testCases: [
      { input: 'cat', shouldMatch: true },
      { input: 'cot', shouldMatch: true },
      { input: 'cut', shouldMatch: true },
      { input: 'ct', shouldMatch: false },
      { input: 'cart', shouldMatch: false },
    ],
    hint: 'Use . to match any single character',
    solution: 'c.t',
  },
  {
    id: 3,
    title: 'Character Classes',
    description: 'Match "cat" or "bat" (but not "rat")',
    type: 'match',
    testCases: [
      { input: 'cat', shouldMatch: true },
      { input: 'bat', shouldMatch: true },
      { input: 'rat', shouldMatch: false },
      { input: 'hat', shouldMatch: false },
      { input: 'category', shouldMatch: true },
    ],
    hint: 'Use [abc] to match any character in the brackets',
    solution: '[cb]at',
  },
  {
    id: 4,
    title: 'Character Ranges',
    description: 'Match any single digit (0-9)',
    type: 'match',
    testCases: [
      { input: '5', shouldMatch: true },
      { input: 'a', shouldMatch: false },
      { input: '42', shouldMatch: true },
      { input: 'abc', shouldMatch: false },
      { input: 'room 123', shouldMatch: true },
    ],
    hint: 'Use [0-9] to match any digit',
    solution: '[0-9]',
  },
  {
    id: 5,
    title: 'Negated Character Classes',
    description: 'Match any character that is NOT a vowel (aeiou)',
    type: 'match',
    testCases: [
      { input: 'b', shouldMatch: true },
      { input: 'a', shouldMatch: false },
      { input: 'xyz', shouldMatch: true },
      { input: 'hello', shouldMatch: true },
      { input: 'aaa', shouldMatch: false },
    ],
    hint: 'Use [^abc] to match any character NOT in the brackets',
    solution: '[^aeiou]',
  },
  {
    id: 6,
    title: 'Shorthand Character Classes',
    description: 'Match any word character (letter, digit, or underscore)',
    type: 'match',
    testCases: [
      { input: 'a', shouldMatch: true },
      { input: '5', shouldMatch: true },
      { input: '_', shouldMatch: true },
      { input: ' ', shouldMatch: false },
      { input: 'hello_123', shouldMatch: true },
    ],
    hint: 'Use \\w to match word characters',
    solution: '\\w',
  },
  {
    id: 7,
    title: 'The Plus Quantifier',
    description: 'Match one or more digits in a row',
    type: 'match',
    testCases: [
      { input: '123', shouldMatch: true },
      { input: '5', shouldMatch: true },
      { input: 'abc', shouldMatch: false },
      { input: 'room 42', shouldMatch: true },
      { input: 'no digits', shouldMatch: false },
    ],
    hint: 'Use + to match one or more of the preceding pattern',
    solution: '\\d+',
  },
  {
    id: 8,
    title: 'The Star Quantifier',
    description: 'Match "go" followed by zero or more "o"s (go, goo, gooo)',
    type: 'match',
    testCases: [
      { input: 'go', shouldMatch: true },
      { input: 'goo', shouldMatch: true },
      { input: 'gooo', shouldMatch: true },
      { input: 'g', shouldMatch: false },
      { input: 'good', shouldMatch: true },
    ],
    hint: 'Use * to match zero or more of the preceding pattern',
    solution: 'goo*',
  },
  {
    id: 9,
    title: 'The Question Mark Quantifier',
    description: 'Match "color" or "colour" (u is optional)',
    type: 'match',
    testCases: [
      { input: 'color', shouldMatch: true },
      { input: 'colour', shouldMatch: true },
      { input: 'colr', shouldMatch: false },
      { input: 'colorful', shouldMatch: true },
      { input: 'colourful', shouldMatch: true },
    ],
    hint: 'Use ? to make the preceding character optional',
    solution: 'colou?r',
  },
  {
    id: 10,
    title: 'Anchors - Start of String',
    description: 'Match "cat" only at the start of the string',
    type: 'match',
    testCases: [
      { input: 'cat', shouldMatch: true },
      { input: 'category', shouldMatch: true },
      { input: 'the cat', shouldMatch: false },
      { input: 'a cat', shouldMatch: false },
      { input: 'catch', shouldMatch: true },
    ],
    hint: 'Use ^ to anchor to the start of the string',
    solution: '^cat',
  },
  {
    id: 11,
    title: 'Anchors - End of String',
    description: 'Match "end" only at the end of the string',
    type: 'match',
    testCases: [
      { input: 'end', shouldMatch: true },
      { input: 'the end', shouldMatch: true },
      { input: 'ending', shouldMatch: false },
      { input: 'end of story', shouldMatch: false },
      { input: 'backend', shouldMatch: true },
    ],
    hint: 'Use $ to anchor to the end of the string',
    solution: 'end$',
  },
  {
    id: 12,
    title: 'Word Boundaries',
    description: 'Match the word "cat" as a complete word (not in "catch" or "scat")',
    type: 'match',
    testCases: [
      { input: 'cat', shouldMatch: true },
      { input: 'the cat', shouldMatch: true },
      { input: 'catch', shouldMatch: false },
      { input: 'scat', shouldMatch: false },
      { input: 'cat!', shouldMatch: true },
    ],
    hint: 'Use \\b for word boundaries',
    solution: '\\bcat\\b',
  },
  {
    id: 13,
    title: 'Alternation',
    description: 'Match "cat" or "dog"',
    type: 'match',
    testCases: [
      { input: 'cat', shouldMatch: true },
      { input: 'dog', shouldMatch: true },
      { input: 'bird', shouldMatch: false },
      { input: 'my cat', shouldMatch: true },
      { input: 'a dog', shouldMatch: true },
    ],
    hint: 'Use | for alternation (OR)',
    solution: 'cat|dog',
  },
  {
    id: 14,
    title: 'Grouping',
    description: 'Match "re" followed by one or more of "pe" or "de"',
    type: 'match',
    testCases: [
      { input: 'repeat', shouldMatch: true },
      { input: 'repent', shouldMatch: true },
      { input: 'redemption', shouldMatch: true },
      { input: 'react', shouldMatch: false },
      { input: 'repepe', shouldMatch: true },
    ],
    hint: 'Use parentheses () to group patterns',
    solution: 're(pe|de)',
  },
  {
    id: 15,
    title: 'Escaping Special Characters',
    description: 'Match a literal dot "." character',
    type: 'match',
    testCases: [
      { input: '.', shouldMatch: true },
      { input: 'a', shouldMatch: false },
      { input: 'file.txt', shouldMatch: true },
      { input: 'hello', shouldMatch: false },
      { input: '...', shouldMatch: true },
    ],
    hint: 'Use backslash \\ to escape special characters',
    solution: '\\.',
  },
] as const;

export const getLesson = (id: number): Lesson | undefined =>
  lessons.find(lesson => lesson.id === id);

export const getNextLesson = (currentId: number): Lesson | undefined =>
  lessons.find(lesson => lesson.id === currentId + 1);
